import { Router, Request, Response, NextFunction } from "express";
import multer from "multer";
import path from "path";
import fs from "fs";
import { HandwritingController } from "../../controllers/handwriting/handwriting.controller";
import { isAuthenticated } from "../../middlewares/utils/auth.middleware";
import { console_util } from "../../utils/console.util";
import Profile from "../../models/core/profile.model";

const router = Router();
const controller = new HandwritingController(Profile);

// ── Multer config ─────────────────────────────────────────────────────────────

// Ensure temp upload dir exists
const uploadDir = path.join(process.cwd(), "tmp", "uploads");
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
    destination: (_req, _file, cb) => cb(null, uploadDir),
    filename:    (_req, file, cb) => {
        const unique = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
        cb(null, `${unique}${path.extname(file.originalname)}`);
    },
});

// Image upload (handwriting sheet — JPG/PNG/HEIC)
const imageUpload = multer({
    storage,
    limits: { fileSize: 20 * 1024 * 1024 }, // 20 MB
    fileFilter: (_req, file, cb) => {
        const allowed = ["image/jpeg", "image/png", "image/heic", "image/webp"];
        if (allowed.includes(file.mimetype)) {
            cb(null, true);
        } else {
            cb(new Error("Only image files are accepted (JPG, PNG, HEIC, WEBP)"));
        }
    },
});

// Font upload (TTF only)
const fontUpload = multer({
    storage,
    limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB
    fileFilter: (_req, file, cb) => {
        const isTtf =
            file.mimetype === "font/ttf" ||
            file.mimetype === "application/x-font-ttf" ||
            file.mimetype === "application/octet-stream" ||
            file.originalname.endsWith(".ttf");

        if (isTtf) {
            cb(null, true);
        } else {
            cb(new Error("Only .ttf font files are accepted"));
        }
    },
});

// ── Logging middleware ────────────────────────────────────────────────────────
router.use((req: Request, _res: Response, next: NextFunction) => {
    console_util.verbose("HandwritingRoutes", `${req.method} ${req.path}`);
    next();
});

// ── Auth ──────────────────────────────────────────────────────────────────────
router.use(isAuthenticated);

// ── Routes ────────────────────────────────────────────────────────────────────

// Upload the filled Calligraphr handwriting sheet (image)
router.post(
    "/upload-sheet",
    imageUpload.single("handwritingSheet"),
    controller.uploadSheet
);

// Upload the TTF font generated by Calligraphr
router.post(
    "/upload-font",
    fontUpload.single("font"),
    controller.uploadFont
);

// Get the current user's handwriting profile
router.get("/profile", controller.getProfile);

// Delete the handwriting profile + Cloudinary assets
router.delete("/profile", controller.deleteProfile);

export default router;